### ISSUE TITLE
 Class 'Rossjcooper\LaravelHubSpot\HubSpotServiceProvider' not found

### ISSUE THREAD

**Issue by KillWil** [rossjcooper/laravel-hubspot#1]
Hello,

I try to embed your provider in my fresh laravel 5.3 and it seems not working...

Class 'Rossjcooper\LaravelHubSpot\HubSpotServiceProvider' not found

Do you have an idea?

**Comment by rossjcooper** [comment]
Hi,
It's been a while since I worked on this, I'll try and take a look and get back to you.

**Comment by matiasvad** [comment]
I have the same issue in Laravel 5.4

**Comment by rossjcooper** [comment]
Hi, I have not worked on this in a long time but I will take a look at it today and try to get it sorted.

**Comment by devudit** [comment]
Same issue with me , Using Laravel 5.4

**Comment by danijelmaric** [comment]
+1

**Comment by jideokus** [comment]
Same here on 5.3. Thanks for looking into it.

**Comment by rossjcooper** [comment]
I believe I have fixed this now everyone, sorry for the delay.
Make sure you are using ^1.0.2

Let me know how you get on.
