### ISSUE TITLE
Turn http_errors off

### ISSUE THREAD

**Issue by WestTexasGuy** [rossjcooper/laravel-hubspot#10]
When using the facade, is there a way to turn off http_errors? For example:
HubSpot::contacts()->getByToken($_COOKIE['hubspotutk']);

**Comment by rossjcooper** [comment]
@WestTexasGuy Thanks for the question/suggestion, I have added this into the config file. Let me know what you think of the PR:

https://github.com/rossjcooper/laravel-hubspot/pull/11

**Comment by rossjcooper** [comment]
I've merged this in now, you can now set the client options in the config file
