### ISSUE TITLE
Compatibility with api v3

### ISSUE THREAD

**Issue by trippo** [rossjcooper/laravel-hubspot#30]
Actually your package use HubSpot/hubspot-php , but there is the new repo HubSpot/hubspot-api-php that uses api v3.
Do you want to update your package to support the new one?

**Comment by rossjcooper** [comment]
@trippo I did originally look into this when they announced it but at the time the new package was missing too much and people where complaining about it. I'll take another look into it and see if its worth updating now. Thanks

**Comment by trippo** [comment]
Great
