### ISSUE TITLE
support for new hubspot api?

### ISSUE THREAD

**Issue by chorton** [rossjcooper/laravel-hubspot#35]
It appears this library is using Hubspot's legacy API and not their new one (hubspot/api-client).

Any plans to start using hubspot/api-client ?

**Comment by ekandreas** [comment]
We have to remove this package due to legacy connection method.

**Comment by rossjcooper** [comment]
Hi, I've made a start on updating to use the new Hubspot API client library https://github.com/rossjcooper/laravel-hubspot/pull/37

**Comment by alexkorsukov** [comment]
Hello @rossjcooper 
The feature is in WIP. Could it be done in near future?

Thank you

**Comment by rossjcooper** [comment]
Sorry for the delay but I have just released v6.0.0 which uses the new api library https://github.com/rossjcooper/laravel-hubspot/pull/37
