### ISSUE TITLE
Update ryanwinchester/hubspot-php version

### ISSUE THREAD

**Issue by limatheus** [rossjcooper/laravel-hubspot#4]
Hi, could you update the dependency **ryanwinchester/hubspot-php** to the latest version (v1.1.1)? 
I noticed that there are some new methods that are missing in version 1.0.
Thank you

**Comment by rossjcooper** [comment]
Will do thanks, unless you want to PR this?

**Comment by limatheus** [comment]
Sure, I will make a PR for this.
Thanks @rossjcooper

**Comment by limatheus** [comment]
Done on PR #5
