### ISSUE TITLE
Publishing does not generate config/hubspot

### ISSUE THREAD

**Issue by callmetwan** [rossjcooper/laravel-hubspot#8]
I had to manually create the config file. Publishing didn't work for me. I didn't get an error, console outputted a success message.

**Comment by rossjcooper** [comment]
Thanks for reporting I'll take a look into this

**Comment by aivis** [comment]
@callmetwan Did you add `HubSpotServiceProvider` to the `config/app.php` before you run the command? 

```
$ php artisan vendor:publish --provider="Rossjcooper\LaravelHubSpot\HubSpotServiceProvider" --tag="config"
Copied File [/vendor/rossjcooper/laravel-hubspot/src/config/hubspot.php] To [/config/hubspot.php]
Publishing complete.
```

```
"laravel/framework": "5.6.*",
```

**Comment by audetcameron** [comment]
if you don't add the service provider first.  just create a hubspot.php file in your config folder and add


```
<?php


return [

    'api_key' => env('HUBSPOT_API_KEY')

];
```

**Comment by pixel-anovak** [comment]
It would be great just to reorder installation steps in readme to make this more clear. Because now adding service provider is on step 5, and creating config file is on step 3.

**Comment by rossjcooper** [comment]
Thanks for the feedback I have updated the readme to be in the correct installation order
